### ISSUE TITLE
Discourage running Arcjet for platform-specific routes like liveness or health checks

### ISSUE THREAD

**Issue by Xe** [arcjet/arcjet-docs#112]
By default when running Arcjet as a middleware, it catches _everything_, including internal probes by Kubernetes or other platforms. Internal probes usually have significantly less information in requests than browsers do. This causes Arcjet decision failures, which can trigger the platform to restart your app, which can cause a CrashLoopBackoff or worse.

The errors you get look like this:

```
 ✦Aj WARN Client IP address is missing. If this is a dev environment set the ARCJET_ENV env var to "development"                                  
 ✦Aj ERROR [analyze wasm] Failed to generate fingerprint: error generating identifier - requested `ip` characteristic but the `ip` value was empty
 ✦Aj ERROR Encountered problem getting remote decision: [failed_precondition] client IP not provided                                              
 Arcjet error [failed_precondition] client IP not provided 
```

The Kubernetes config that can trigger this looks something like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app
spec:
  template:
    spec:
      containers:
        - name: main
          livenessProbe:
            httpGet:
              path: /_healthz
              port: 3000
              httpHeaders:
                - name: user-agent
                  value: "healthz"
```

This is fixed by adjusting the middleware regex to include space for a "health" route (for example at `/_healthz`):

```diff
 export const config = {
   // matcher tells Next.js which routes to run the middleware on.
   // This runs the middleware on all routes except for static assets.
-  matcher: ["/((?!_next/static|_next/image|favicon.ico).*)"],
+  matcher: ["/((?!_next/static|_next/image|favicon.ico|_healthz).*)"],
 };
```

And then adding a route for that healthcheck:

```ts
// src/app/_healthz/route.ts
import { NextRequest, NextResponse } from "next/server";

export const GET = async (req: NextRequest) => {
  if (req.headers.get("user-agent") !== "healthz") {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  return new Response("OK", {
    status: 200,
    headers: {
      "Content-Type": "text/plain",
    },
  });
};
```
